name: Build iOS Native App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Build and Archive App
      run: |
        echo "Building R7X-Tolls for HAMA⚡️VIP..."
        # کۆمایڵکردنی فایله نەیتیڤەکان
        swiftc -parse-as-library main.swift AppDelegate.swift -o R7X-Tolls
        ls -la
